#!/bin/bash

#           ask for info on flash processes                          make into csv  search for relevant lines
LSOF_INFO=$(lsof -M -n -p $(pidof plugin-container pluginloader.exe | tr ' ' ',') | egrep '/tmp/Flash|/Temp/')

#       echo our FD info    strip rwu after FD               map to /proc names
FILES=$(echo "$LSOF_INFO" | sed 's?\([0-9]\)[a-zA-Z]?\1?g' | awk '{ printf "/proc/%s/fd/%s ",$2,$4; }')

echo "FILES:'${FILES}'"
vlc $FILES
exit $?
